/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ShopDemo.view.MainView', {
    extend: 'Ext.tab.Panel',

    requires: [
        'Ext.tab.Bar',
        'Ext.navigation.View',
        'Ext.navigation.Bar',
        'Ext.Label',
        'Ext.Button',
        'Ext.dataview.List',
        'Ext.XTemplate',
        'Ext.MessageBox'
    ],

    config: {
        itemId: 'mainview',
        tabBar: {
            docked: 'bottom'
        },
        items: [
            {
                xtype: 'navigationview',
                title: '首页',
                iconCls: 'home',
                itemId: 'home',
                navigationBar: {
                    docked: 'top',
                    itemId: 'topBar',
                    items: [
                        {
                            xtype: 'label',
                            html: '<img src=\'resources/icons/Icon_Android36.png\'></img>乐活烘培',
                            itemId: 'icon'
                        },
                        {
                            xtype: 'button',
                            align: 'right',
                            itemId: 'login',
                            ui: 'action',
                            text: '登录'
                        },
                        {
                            xtype: 'button',
                            align: 'right',
                            itemId: 'register',
                            ui: 'action',
                            text: '注册'
                        }
                    ]
                }
            },
            {
                xtype: 'container',
                title: '分类',
                iconCls: 'list',
                itemId: 'category',
                layout: 'card',
                items: [
                    {
                        xtype: 'list',
                        centered: false,
                        docked: 'left',
                        itemId: 'mylist',
                        width: 100,
                        hideOnMaskTap: false,
                        modal: false,
                        itemTpl: [
                            '{categoryName}'
                        ],
                        store: 'CategoryStore',
                        triggerCtEvent: 'singletap',
                        triggerEvent: 'itemsingletap',
                        grouped: false,
                        onItemDisclosure: false
                    },
                    {
                        xtype: 'dataview',
                        baseCls: 'Product',
                        styleHtmlContent: true,
                        itemTpl: [
                            '<tpl for=".">',
                            '<div class="Product">',
                            '<div class="Product_img"><img src="{url}" /></div>',
                            '<div class="Product_info">',
                            '<h3>{productName}</h3><h4>价格:{price}</h4>',
                            '<p>{description}</p>',
                            '</div>',
                            '</div>',
                            '</tpl>'
                        ],
                        store: 'ProductStore'
                    }
                ]
            },
            {
                xtype: 'container',
                title: '购物车',
                iconCls: 'cart',
                itemId: 'cart'
            },
            {
                xtype: 'container',
                title: '我的信息',
                iconCls: 'user',
                itemId: 'myinfo'
            }
        ],
        listeners: [
            {
                fn: 'onMylistSelect',
                event: 'select',
                delegate: '#mylist'
            }
        ]
    },

    onMylistSelect: function(dataview, record, eOpts) {

        Ext.Msg.alert('Selected!', 'You selected ' + record.get('name'));
    }

});