/*
 * File: app/view/MyNavigationView1.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ShopDemo.view.MyNavigationView1', {
    extend: 'Ext.navigation.View',
    alias: 'widget.mynavigationview1',

    requires: [
        'Ext.navigation.Bar',
        'Ext.Label',
        'Ext.Button'
    ],

    config: {
        itemId: 'home',
        navigationBar: {
            docked: 'top',
            itemId: 'topBar',
            items: [
                {
                    xtype: 'label',
                    html: '<img src=\'resources/icons/Icon_Android36.png\'></img>乐活烘培',
                    itemId: 'icon'
                },
                {
                    xtype: 'button',
                    align: 'right',
                    itemId: 'login',
                    ui: 'action',
                    text: '登录'
                },
                {
                    xtype: 'button',
                    align: 'right',
                    itemId: 'register',
                    ui: 'action',
                    text: '注册'
                }
            ]
        }
    }

});